global:
  scrape_interval: ${SCRAPE_INTERVAL}
  
rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: "go-app"
    static_configs:
      - targets: ["go-app:8080"]
      
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

